spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8081

name: "prod"
management:
  endpoints:
    web:
      exposure:
        include: "*"





#server:
#  port: 8082
#name: "prod"