spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.134:8848
server:
  port: 8081

name: "prod"
management:
  endpoints:
    web:
      exposure:
        include: "*"





#server:
#  port: 8082
#name: "prod"