spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.134:8848
server:
  port: 8081

name: "dev"
management:
  endpoints:
    web:
      exposure:
        include: "*"