spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.134:8848
        group: api-gateway
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: NACOS-CONSUMER
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://nacos-consumer
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Method=GET,POST

        - id: NACOS-CONSUMER-FEIGN
          uri: lb://nacos-consumer-feign
          predicates:
            - Method=GET,POST

        - id: NACOS-CONSUMER-FEIGN
          uri: lb://nacos-provider
          predicates:
              - Method=GET,POST
## 使用 Sentinel 作为熔断器
#    sentinel:
#      transport:
#        dashboard:
#        port:
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: "*"





#server:
#  port: 8080
#
#name: "local"
#
#spring:
#  datasource:
#    name: springboot
#    type: com.alibaba.druid.pool.DruidDataSource
#    #druid相关配置
#    druid:
#      #监控统计拦截的filters
#      filter: stat
#      #mysql驱动
#      driver-class-name: com.mysql.jdbc.Driver
#      #基本属性
#      url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&allowMultiQueries=TRUE&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#      username: root
#      password: root
#      #配置初始化大小/最小/最大
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      #获取连接等待超时时间
#      max-wait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#
#  #mybatis配置
#mybatis:
#    mapper-locations: classpath:/mapping/*.xml
#    type-aliases-package: com.lppz.entity.dto
#
##pagehelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
