spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: api-gateway
server:
  port: 9000

name: "dev"
management:
  endpoints:
    web:
      exposure:
        include: "*"






#server:
#  port: 8082
#name: "prod"