spring:
  application:
    name: nacos-consumer-feigh
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: consumer-feigh
server:
  port: 9991

name: "prod"
management:
  endpoints:
    web:
      exposure:
        include: "*"






#server:
#  port: 8082
#name: "prod"