spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.25.128:8848
        group: consumer-feign
server:
  port: 9991

name: "prod"
management:
  endpoints:
    web:
      exposure:
        include: "*"






#server:
#  port: 8082
#name: "prod"